repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        stages: [pre-commit]
      - id: terraform_tflint
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        stages: [pre-commit, manual]
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
        stages: [pre-commit, manual]
      - id: check-case-conflict
        stages: [pre-commit, manual]
      - id: check-symlinks
        stages: [pre-commit, manual]
      - id: check-json
        stages: [pre-commit, manual]
      - id: mixed-line-ending
        args:
        - --fix=lf
        stages: [pre-commit, manual]
      - id: no-commit-to-branch
        args:
        - --branch
        - main
        stages: [pre-commit, manual]
      - id: pretty-format-json
        args:
        - --autofix
        - --no-sort-keys
        stages: [pre-commit, manual]
