apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app: demo-app
      allow-ingress-traefik: "true"
    includeSelectors: true

images:
  - name: clearroute/demo-app-frontend
    newName: 799468650620.dkr.ecr.ap-southeast-2.amazonaws.com/demo-app-2-frontend-prod
    newTag: 0.0.1

replacements:
  - sourceValue: demo-app-2-prod.dev.clearroute.io
    targets:
      - select:
          kind: Ingress
          name: demo-app
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        options:
          create: true
