apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platformcon2026-dev-apps
  namespace: argocd
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/clear-route/platformcon2026-pr-driven-idp.git
        revision: main
        directories:
          - path: applications/**/k8s/overlays/dev
  template:
    metadata:
      name: 'platformcon2026-dev-{{ index .path.segments 1 }}'
      annotations:
        argocd-diff-preview/watch-pattern: applications/{{ index .path.segments 1 }}/k8s/overlays/dev/.*, applications/{{ index .path.segments 1 }}/k8s/base/.*
    spec:
      project: default
      sources:
        - repoURL: https://github.com/clear-route/platformcon2026-pr-driven-idp.git
          targetRevision: main
          path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'platformcon2026-dev-{{ index .path.segments 1 }}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            # attach default deny policy on the namespace
            deny-default-all: "true"
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
