apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platformcon2026-demo-preview-appset
  namespace: argocd
  annotations:
    argocd-diff-preview/ignore: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: clear-route
          repo: platformcon2026-pr-driven-idp
          appSecretName: constellation-iac
          labels:
            - preview
  template:
    metadata:
      name: 'platformcon2026-demo-preview-app-{{ index .path.segments 2 }}-pr-{{.number}}'
      annotations:
        # subscribing to the PR comment for preview environments
        notifications.argoproj.io/subscribe.on-deployed.github: ""

        # injecting annotations to use for the pull request comment
        argocd-preview/frontend-hostname: "{{ index .path.segments 1 }}-pr-{{.number}}.dev.clearroute.io"
        argocd-preview/backend-hostname: "api.{{ index .path.segments 1 }}-pr-{{.number}}.dev.clearroute.io"
        argocd-preview/namespace: "preview-app-{{ index .path.segments 1 }}-{{ index .path.segments 1 }}-pr-{{.number}}"
        argocd-preview/app-name: "{{ index .path.segments 1 }}"
        argocd-preview/pr-git-sha: "{{ .head_short_sha_7 }}"
        argocd-preview/pr-author: "{{ .author }}"
    spec:
      project: default
      # multi sources currently not supported with Github Notifications (https://github.com/argoproj/notifications-engine/issues/224)
      source:
        repoURL: https://github.com/clear-route/platformcon2026-pr-driven-idp.git
        targetRevision: dev
        path: '{{ .path.path }}'
        kustomize:
          patches:
            # patch preview-values configmap used for kustomize replacements
            - target:
                kind: ConfigMap
                name: preview-values
              patch: |
                - op: add
                  path: /data
                  value:
                    frontend-hostname: "{{ index .path.segments 1 }}-pr-{{.number}}.dev.clearroute.io"
                    backend-hostname: "api.{{ index .path.segments 1 }}-pr-{{.number}}.dev.clearroute.io"
                    namespace: "preview-app-{{ index .path.segments 1 }}-{{ index .path.segments 1 }}-pr-{{.number}}"
                    app-name: "{{ index .path.segments 1 }}"
                    pr-git-sha: "{{ .head_short_sha_7 }}"
                    pr-author: "{{ .author }}"
          commonAnnotations:
            link.argocd.argoproj.io/external-link: https://github.com/clear-route/{{ index .path.segments 1 }}/pull/{{.number}}
      destination:
        server: https://kubernetes.default.svc
        namespace: 'platformcon2026-demo-preview-app-{{ index .path.segments 1 }}-pr-{{.number}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            # attach default deny policy on the namespace
            deny-default-all: "true"
            allow-passport: "true"
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
