apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-frontend
  labels:
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: frontend
        image: 799468650620.dkr.ecr.ap-southeast-2.amazonaws.com/demo-app-frontend-dev:0.0.0-000000
        env:
          - name: HOSTNAME
            value: "0.0.0.0"
          - name: PORT
            value: "3000"
        ports:
        - containerPort: 3000
