# App secrets (combined from multiple sources in overlay)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: secrets
