apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../../kustomize/rds-db-provisioning

labels:
  - pairs:
      app: hiring-tracker
      allow-ingress-traefik: "true"
      allow-egress-rds: "true"
    includeSelectors: true

images:
  - name: 799468650620.dkr.ecr.ap-southeast-2.amazonaws.com/hiring-tracker-frontend-dev
    newTag: 0.0.0-3938d03

configMapGenerator:
  - name: rds-provisioning-scripts
    files:
      - files/db-provisioning.sh
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation

  - name: frontend
    literals:
      - NEXT_PUBLIC_PASSPORT_URL="https://passport.dev.clearroute.io"
      - NEXT_PUBLIC_COOKIE_DOMAIN=".dev.clearroute.io"
      - APP_ENVIRONMENT="development"
      - DB_SSL_MODE="require"

patches:
  - target:
      kind: ExternalSecret
      name: secrets
    patch: |
      - op: add
        path: /spec/dataFrom
        value:
          - extract:
              key: constellation/dev/rds_credentials
          - extract:
              key: constellation/hiring-tracker/dev

  - target:
      kind: Deployment
      name: hiring-tracker
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secrets
              key: PGHOST
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secrets
              key: PGPORT

replacements:
  - sourceValue: hiring-tracker.dev.clearroute.io
    targets:
      - select:
          kind: Ingress
          name: hiring-tracker
        fieldPaths:
          - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        options:
          create: true
