name: Publish

on:
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-images:
    uses: clear-route/constellation-core/.github/workflows/docker-publish.yaml@main
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: demo-app
            dockerfile: Dockerfile
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      environment: ${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}
      app-name: ${{ github.event.repository.name }}
      dockerfile-path: ${{ matrix.component.dockerfile }}
      component: ${{ matrix.component.name }}
